In [1]:
import sys,os

sys.path.append(os.path.join(os.environ['ATS_SRC_DIR'],'tools','meshing_ats'))
import meshing_ats

sys.path.append(os.path.join(os.environ['HOME'],'research','python'))
import smoothing

import numpy as np
from matplotlib import pyplot as plt

In [7]:
# 1 km long hillslope, 10% slope
x = np.linspace(0,1000,101)
z = np.linspace(100,0,101)
print x, z


[    0.    10.    20.    30.    40.    50.    60.    70.    80.    90.
   100.   110.   120.   130.   140.   150.   160.   170.   180.   190.
   200.   210.   220.   230.   240.   250.   260.   270.   280.   290.
   300.   310.   320.   330.   340.   350.   360.   370.   380.   390.
   400.   410.   420.   430.   440.   450.   460.   470.   480.   490.
   500.   510.   520.   530.   540.   550.   560.   570.   580.   590.
   600.   610.   620.   630.   640.   650.   660.   670.   680.   690.
   700.   710.   720.   730.   740.   750.   760.   770.   780.   790.
   800.   810.   820.   830.   840.   850.   860.   870.   880.   890.
   900.   910.   920.   930.   940.   950.   960.   970.   980.   990.
  1000.] [ 100.   99.   98.   97.   96.   95.   94.   93.   92.   91.   90.   89.
   88.   87.   86.   85.   84.   83.   82.   81.   80.   79.   78.   77.
   76.   75.   74.   73.   72.   71.   70.   69.   68.   67.   66.   65.
   64.   63.   62.   61.   60.   59.   58.   57.   56.   55.  

In [8]:
m2 = meshing_ats.Mesh2D.from_Transect(x,z)

In [24]:
# layer extrusion
layer_types = []
layer_data = []
layer_ncells = []
layer_mat_ids = []

layer_types.append("constant")
layer_data.append(0.14)
layer_ncells.append(7)
layer_mat_ids.append(1001)

layer_types.append('constant')
layer_data.append(0.4)
layer_ncells.append(20)
layer_mat_ids.append(1002)

dz = .02
for i in range(15):
    dz *= 1.2
    layer_types.append("constant")
    layer_data.append(dz)
    layer_ncells.append(1)
    layer_mat_ids.append(1002)
        
for i in range(5):
    dz *= 2
    layer_types.append("constant")
    layer_data.append(dz)
    layer_ncells.append(1)
    layer_mat_ids.append(101)
    
layer_types.append('constant')
layer_data.append(45 - sum(layer_data))
layer_ncells.append(2)
layer_mat_ids.append(101)

print np.array([layer_data, np.cumsum(np.array(layer_data)), layer_mat_ids]).transpose()
print layer_mat_ids
print sum(layer_ncells)

m3 = meshing_ats.Mesh3D.extruded_Mesh2D(m2, layer_types, 
                                       layer_data, 
                                      layer_ncells, 
                                     layer_mat_ids)
m3.write_exodus("hillslope.exo")


[[  1.40000000e-01   1.40000000e-01   1.00100000e+03]
 [  4.00000000e-01   5.40000000e-01   1.00200000e+03]
 [  2.40000000e-02   5.64000000e-01   1.00200000e+03]
 [  2.88000000e-02   5.92800000e-01   1.00200000e+03]
 [  3.45600000e-02   6.27360000e-01   1.00200000e+03]
 [  4.14720000e-02   6.68832000e-01   1.00200000e+03]
 [  4.97664000e-02   7.18598400e-01   1.00200000e+03]
 [  5.97196800e-02   7.78318080e-01   1.00200000e+03]
 [  7.16636160e-02   8.49981696e-01   1.00200000e+03]
 [  8.59963392e-02   9.35978035e-01   1.00200000e+03]
 [  1.03195607e-01   1.03917364e+00   1.00200000e+03]
 [  1.23834728e-01   1.16300837e+00   1.00200000e+03]
 [  1.48601674e-01   1.31161004e+00   1.00200000e+03]
 [  1.78322009e-01   1.48993205e+00   1.00200000e+03]
 [  2.13986411e-01   1.70391846e+00   1.00200000e+03]
 [  2.56783693e-01   1.96070216e+00   1.00200000e+03]
 [  3.08140431e-01   2.26884259e+00   1.00200000e+03]
 [  6.16280863e-01   2.88512345e+00   1.01000000e+02]
 [  1.23256173e+00   4.11768

In [25]:
x = np.array([0,1])
z = np.array([0,0])
m2 = meshing_ats.Mesh2D.from_Transect(x,z)

m3 = meshing_ats.Mesh3D.extruded_Mesh2D(m2, layer_types, 
                                       layer_data, 
                                      layer_ncells, 
                                     layer_mat_ids)
m3.write_exodus("hillslope_column.exo")


You are using exodus.py v 1.04 (beta-cmake), a python wrapper of some of the exodus II library.
Copyright (c) 2013, 2014, 2015, 2016 Sandia Corporation. Under the terms of Contract DE-AC04-94AL85000
with Sandia Corporation, the U.S. Government retains certain rights in this software.

Opening exodus file: hillslope_column.exo
Closing exodus file: hillslope_column.exo
